// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UndoCloseTab
{
    internal sealed partial class Vsix
    {
        public const string Id = "UndoCloseTab.c49b9288-9c5f-495e-805d-f9427c015175";
        public const string Name = "Undo Close Tab";
        public const string Description = @"Reopens the previously closed tab.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "reduckted";
        public const string Tags = "";
    }
}
