// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UndoCloseTab
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "7696de46-379a-4a1d-99bf-bc10fdca6d3f";
        public static Guid Package = new Guid(PackageString);

        public const string guidSHLMainMenuExtraString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenuExtra = new Guid(guidSHLMainMenuExtraString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int UndoCommand = 0x0100;
        public const int UndoGroup = 0x0200;
        public const int IDG_VS_EZ_DOCWELLOPS = 0x0742;
    }
}